### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by tomingrad** [agarian-2/MultiOgar#10]
when i try connecting on a official agar.io, it doesn't work

when i try this:
**core.disableIntegrityChecks(true);
core.connect("ws://localhost:443");**

it gives me "undefined" and in console: 
**[INFO] A new player has connected to the server.
[INFO] An unnamed cell has disconnected from the server.**

and when i try this:
**core.disableIntegrityChecks(true);
core.connect("wss://localhost:443");**

it gives me this:
**WebSocket connection to 'wss://localhost/' failed**

Any ideas?

**Comment by agarian-2** [comment]
It's worth noting that pretty much everyone (including me) no longer updates the server-side protocol to work with modern agar.io, due to how often it changed back in the day. Not sure about nowadays, but I don't plan to update it either (don't have the time or skillset lol). Which is kinda why I have a client made for this server at https://agarian-2.github.io.
